# Generated by Django 5.2.13 on 2026-04-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='bi-award', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='portfolio_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='verified_certifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='verified_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='verified_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='verified_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='verified_skills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.message')),
            ],
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='reputation_badges',
            field=models.ManyToManyField(blank=True, related_name='artisans', to='users.reputationbadge'),
        ),
    ]
